// Builds public/icons/icon.svg: granny square in the four page colours as
// continuous rings of stitches, last round in progress with the hook.
// Usage: npm run icons (also regenerates every PNG size)
import { writeFileSync } from 'node:fs';

const C = 67.5;
const W = 3, H = 8, STEP = 4.4, CORNER = 5;
const rounds = [
  { h: 10, color: '#B8336A' },
  { h: 20, color: '#6D4BC3' },
  { h: 30, color: '#0E7C7B' },
  { h: 40, color: '#4169E1' },
];

// one stitch centred on (x, y), standing across the ring; angle in degrees
const post = (x, y, angle, color) =>
  `<rect x="${(x - W / 2).toFixed(2)}" y="${(y - H / 2).toFixed(2)}" width="${W}" height="${H}" rx="1.5" fill="${color}"` +
  (angle ? ` transform="rotate(${angle} ${x.toFixed(2)} ${y.toFixed(2)})"` : '') + '/>';

const parts = [];
for (const [ri, { h, color }] of rounds.entries()) {
  const inProgress = ri === rounds.length - 1; // last round stops partway up the left side
  const span = h - CORNER;
  const n = Math.max(1, Math.round((2 * span) / STEP) + 1);
  const ts = Array.from({ length: n }, (_, i) => (n === 1 ? 0 : -span + (2 * span * i) / (n - 1)));
  for (const t of ts) {
    parts.push(post(C + t, C - h, 0, color)); // top
    parts.push(post(C + h, C + t, 90, color)); // right
    parts.push(post(C + t, C + h, 0, color)); // bottom
    if (!inProgress || t > 4) parts.push(post(C - h, C + t, 90, color)); // left
  }
  parts.push(post(C + h, C - h, 45, color), post(C + h, C + h, -45, color), post(C - h, C + h, 45, color));
  if (!inProgress) parts.push(post(C - h, C - h, -45, color));
}

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="-4 0 128 128">
  <!-- Generated by scripts/make-icon.mjs -->
  <rect x="-4" y="0" width="128" height="128" fill="#E4EEF9"/>
  ${parts.join('\n  ')}
  <line x1="27.5" y1="64" x2="12" y2="20" stroke="#F6B93B" stroke-width="6" stroke-linecap="round"/>
  <path d="M27.5 64 C30 70 23 73 21 68" fill="none" stroke="#F6B93B" stroke-width="4.5" stroke-linecap="round"/>
</svg>
`;
writeFileSync(new URL('../public/icons/icon.svg', import.meta.url), svg);
